# Generated by Django 5.1.1 on 2024-10-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginatorapp', '0002_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='number_of_page',
            new_name='number_of_posts',
        ),
    ]
