# Generated by Django 5.1.1 on 2024-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginatorapp', '0003_rename_number_of_page_pages_number_of_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='number_of_posts',
            field=models.IntegerField(default=2),
        ),
    ]
